[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter direct-transfair-backend prisma:generate",
  "pnpm --filter direct-transfair-backend prisma:platform:generate",
  "pnpm build:backend"
]

[start]
cmd = "pnpm start:backend:prod"