ALTER TABLE "commission_configs" ADD COLUMN IF NOT EXISTS "feeRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "commission_configs" ADD COLUMN IF NOT EXISTS "fixedFee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "commission_configs" ADD COLUMN IF NOT EXISTS "payoutMethod" TEXT;